### PR TITLE
[deps] Upgraded QA dependencies

### PR DESCRIPTION
**Pull request by pandafy**
- Bummped black~=23.3.0
- Bumped flake8~=6.0.0
- Bumped readme-renderer~=37.3.0
- Bumped coveralls~=3.3.0

### CODE REVIEW

**Review by nemesifier — CHANGES_REQUESTED** [review]
Please rebase on the latest master.

Can you check whether upgrading black changes the formatting?

**Comment by pandafy** [comment]
Yes, it does.

**Comment by nemesifier** [comment]
> > Can you check whether upgrading black changes the formatting in other modules (eg: controller)?
> 
> Yes, it does.

Can you please look if there is there any flag we can add to avoid that? Maybe when they changed the default they provided a way to override it.

**Comment by pandafy** [comment]
@nemesifier  I cannot find such a flag in https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#command-line-options

**Comment by nemesifier** [comment]
> @nemesifier I cannot find such a flag in https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#command-line-options

What about: https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#versions ?

**Comment by pandafy** [comment]
Did you mean using the `--required-version` flag? It will only stop the execution of the black command 


```
black --required-version 21.9b0 -c "format = 'this'"
format = "this"
black --required-version 31.5b2 -c "still = 'beta?!'"
Oh no! 💥 💔 💥 The required version does not match the running version!
```

**Comment by nemesifier** [comment]
Handled this in https://github.com/openwisp/openwisp-utils/pull/389.

**Pull request closed without merging**
