### PR TITLE
adding django2.0 compatibility.

### PR DESCRIPTION
**Pull request by gandhi23**
Changes have been made to openwisp-utils directory to add django2 compatibility. This is a part of my google code-in task:  https://codein.withgoogle.com/dashboard/task-instances/5332094102274048/

### CODE REVIEW

**Comment by phyxkal** [comment]
maybe mentor will say this is wrong

**Comment by gandhi23** [comment]
@rohithasrk for ur kind notice, django2 is not backward-compatible with previous django versions. So, it is impossible to add both. :)

**Comment by gandhi23** [comment]
@nemesisdesign only necessary change have been made. if not, please say the specific changes to be made in chat or here.

**Comment by rohithasrk** [comment]
@gandhi23 It is only true for some of the changes @gandhi23. Not all of django2.0 is different from django1.11

**Comment by rohithasrk** [comment]
Check out this https://github.com/netjson/django-netjsongraph

**Pull request closed without merging**
