### PR TITLE
[qa] Added a check for empty line at the end of a file #29

### LINKED ISSUE #29: [qa] Add a check for empty line at the end of a file
We should add another automated test to check if all the files have an empty line at the end of the file.
Many GCI students are making this mistake and an automated test will help them in my opinion! :smile: 

PS: **binary files must be ignored**, the check should be performed only on text files.
If it can be performed with just a series of shell commands, we can use that and start adding this check to the `.travis.yml` build of this repo

### PR DESCRIPTION
**Pull request by unsuitable001**
I have created an alternative implementation what Reza already did.
I'm sorry that I couldn't make it in GCI. I tried to make it cleaner
and also written a script to add newlines at the end, which is available at : https://github.com/unsuitable001/usnippet/blob/master/addendline.sh

Closes #37 

Fixes #29

### CODE REVIEW

**Comment by nemesisdesign** [comment]
It's not clear what is the improvement and what problem the improvement is trying to solve, can you expand on that?

**Comment by unsuitable001** [comment]
I'll prefer to wait until you guys test it (I already have tested it). As, Reza already implemented it (not merged yet though), it can just be an alternative (and simple, short) implementation.
I'd like to wait & work on forks.

**Comment by unsuitable001** [comment]
@nemesisdesign Done.

**Comment by unsuitable001** [comment]
As you can see, conflict is in `travis.yml` file. I think, this is because, Reza's PR is merged while it's open. And, her script's name is different than mine. Probably this thing caused conflict. 

I'll rename the file as her...

**Comment by unsuitable001** [comment]
@nemesisdesign @atb00ker I can't rebase because there was the conflict. Git is not allowing me. It always says
```
CONFLICT (content): Merge conflict in .travis.yml
error: could not apply 294b47d... [qa] Added a check for empty line at the end of a file #29

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
```

**Comment by unsuitable001** [comment]
nemesisdesign atb00ker Done 😄 . I can't rebase it though. It says :

CONFLICT (content): Merge conflict in .travis.yml
error: could not apply 294b47d... [qa] Added a check for empty line at the end of a file #29

**Comment by atb00ker** [comment]
@unsuitable001 you'll need to make the changes in the file with conflict and then do `git rebase --continue`. 
If you need help with this, you can watch a video of this on YouTube or ask on the Gitter channel! :smile:

**Comment by unsuitable001** [comment]
@atb00ker Actually, I fixed the conflict & pushed it. That's why GitHub is not showing any conflict (as there's none). But, if I try to rebase to a previous commit (where the conflict actually occurred) is giving me error.
I'll try to rebase if I can. I don't think it's much of an issue to have just 2 commits.

**Comment by atb00ker** [comment]
@unsuitable001 It might look like a small thing to make it in one commit now, but it's important, over time, a clean history makes management much simpler. We wouldn't remember the reason for these changes some time down the road, tracking a clean history tree would be much simpler at that time. Wouldn't you agree? :smile:

**Comment by unsuitable001** [comment]
@atb00ker Yes. I totally agree with you. I'll try to rebase. I'm just saying that, there's a chance that it can't be rebased. In that case, we should just leave it like that.

Look, there's some commit created by other people between my current commit & the commit I want to be the 'base' . & There's also some conflict. I can't just override commits that I didn't even authored. So..... Yeah... I'm confused

**Comment by atb00ker** [comment]
It's alright, when learning git, it can be confusing at times.
Use these commands if you getting frustrated trying to fix it:
```
git fetch upstream master
git reset --hard upstream/master
git cherry-pick 294b47dcd192cebe2d5749c2752dc0ef10bfdcfc
# solve the conflicts and make the desired changes
git add .
git commit
git push -f
```
Remember almost all git problems i've come across so far have been fixable, so don't doubt that git can't do it, just google and ask on Gitter but learning these basic commands in absolutely crucial. :smile:

**Comment by unsuitable001** [comment]
Thanks @atb00ker . It worked!! Now you can review. Done @nemesisdesign .

**Pull request merged**
