### PR TITLE
[Fix] Fixed shifting of html due to main-menu #153

### LINKED ISSUE #153: [bug] Html get shifted left due to main-menu
I don't know wheater it was done intentionally or not but when the cursor is moved to the right side cursor change into pointer due to the main menu which is not visible as shown in the figure.

Screenshot (145)

This is causing some other problem. 

Steps to produce:
1. Click on the invisible portion shown in above figure, it will take you to a different page.
2. Click back button and you will see that html get shifted left due to main menu like this.
Screenshot (146)

### PR DESCRIPTION
**Pull request by niteshsinha17**
Fixes #153

### CODE REVIEW

**Review by pandafy — CHANGES_REQUESTED** [review]
@niteshsinha17 the current solution is not robust and does not works with all screen sizes. I was still able to reproduce the bug even in your patch. 

image

I will suggest to investigate why this happens in the first place.

**Comment by niteshsinha17** [comment]
> @niteshsinha17 the current solution is not robust and does not works with all screen sizes. I was still able to reproduce the bug even in your patch.
Okay I will check

**Comment by niteshsinha17** [comment]
@pandafy I will look on it.

**Review by pandafy — APPROVED** [review]
LGTM :+1:

**Review by atb00ker — APPROVED** [review]
LGTM! :+1: 

Thanks @niteshsinha17 :smile:

**Pull request merged**
